# Generated by Django 4.1 on 2022-10-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_total_answer_question_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='role_user',
            field=models.TextField(default='bumil'),
        ),
        migrations.AddField(
            model_name='question',
            name='role_user',
            field=models.TextField(default='bumil'),
        ),
    ]
