# Generated by Django 4.1 on 2022-11-02 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(blank=True, default='', max_length=32)),
                ('tanggal', models.DateField(default='')),
                ('waktu', models.CharField(default='', max_length=32)),
                ('kapasitas_balita', models.IntegerField(default='')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'ordering': ('-uploaded',),
            },
        ),
    ]
