# Generated by Django 4.1 on 2022-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0002_note_delete_informasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tanggal',
            field=models.DateTimeField(default='', max_length=32, null=True),
        ),
    ]
