# Generated by Django 4.1 on 2022-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0002_note_delete_informasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(blank=True, default='', max_length=32)),
                ('tanggal', models.CharField(blank=True, default='', max_length=32)),
                ('waktu', models.TextField(blank=True, default='')),
                ('kapasitas_balita', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
