# Generated by Django 4.1 on 2022-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0003_informasi_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('uploaded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-uploaded',),
            },
        ),
        migrations.DeleteModel(
            name='Informasi',
        ),
    ]
