# Generated by Django 4.1 on 2022-10-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0004_note_delete_informasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='sender',
            new_name='lokasi',
        ),
        migrations.RemoveField(
            model_name='note',
            name='message',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='kapasitas_balita',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='note',
            name='tanggal',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='note',
            name='waktu',
            field=models.CharField(default='', max_length=32),
        ),
    ]
