# Generated by Django 4.1 on 2022-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='is_bumil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='is_faskes',
            field=models.BooleanField(default=False),
        ),
    ]
