# Generated by Django 4.1 on 2022-10-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_roleuser_is_admin_roleuser_is_bumil_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
