# Generated by Django 4.1 on 2022-12-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_kesehatan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
