# Generated by Django 4.1 on 2022-10-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarybund', '0002_alter_diarybund_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarybund',
            name='date',
            field=models.DateField(),
        ),
    ]
